import Head from 'next/head'
import Link from 'next/link'
import Menu from '../componentes/menu/menu'
import Title from '../componentes/title/title'
import styles from '../styles/Home.module.css'
import SwiperCore, { Parallax, Navigation, Mousewheel, Pagination } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import "swiper/swiper.min.css";
import "swiper/components/navigation/navigation.min.css"
SwiperCore.use([Parallax,Pagination,Mousewheel,Navigation])
import { Fragment } from 'react';
import Footer from '../componentes/footer/footer'
import Slide from '../componentes/slide/slide'

export default function Home({trendingProps,actionProps,comedyProps}) {
  return (
    <Fragment>
    <Head>
      <meta name="theme-color" content="#161616" />
      <meta name="apple-mobile-web-app-status-bar-style" content="#161616" />
      <meta name="msapplication-navbutton-color" content="#161616" />
      <title>Reactflix</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Menu></Menu>
    <Swiper speed={600} parallax={true} pagination={{
      "clickable": true}} navigation={true} className="mySwiper">
      <SwiperSlide>
        <div className={styles.backdrop_skeleton}>
          <div className={styles.backdrop_skeleton_absolute}>
            <img className={styles.swiper_img} src="https://www.themoviedb.org/t/p/original/6S159wVNvQfwoQh5yBxWKCsI1YL.jpg"/>
            <div className={styles.box_text}>
              <div className={styles.box_row_flex}>
                <h1 data-swiper-parallax="-900">O dilema das redes</h1>
                <p data-swiper-parallax="-700">Especialistas em tecnologia e profissionais da área fazem um alerta: as redes sociais podem ter um impacto devastador sobre a democracia e a humanidade.</p>
                <Link href="#">
                  <a className="buttom">info</a>
                </Link>
              </div>
            </div>
            <div className="shadow"></div>
          </div>
        </div>
      </SwiperSlide>
      <SwiperSlide>
        <img className={styles.swiper_img} src="https://www.themoviedb.org/t/p/original/ktZaQ4FEmKpRgetiBooZETYQbmQ.jpg"/>
        <div className={styles.box_text}>
          <div className={styles.box_row_flex}>
            <h1 data-swiper-parallax="-900">O gambito da rainha</h1>
            <p data-swiper-parallax="-700">Durante a Guerra Fria, em um orfanato do Kentucky, uma garota prodígio do xadrez luta contra o vício para se tornar a número um do mundo.</p>
            <Link href="#">
              <a className="buttom">info</a>
            </Link>
          </div>
        </div>
        <div className="shadow"></div>
      </SwiperSlide>
    </Swiper>
      <div className={styles.container_cards} id="wrapper_cards">
        <Title title="trending"/>
        <Slide array={trendingProps}/>
        <Title title="ação"/>
        <Slide array={actionProps}/>
        <Title title="comédia"/>
        <Slide array={comedyProps}/>
      </div>
      <Footer></Footer>
    </Fragment>
  )
}

export async function getServerSideProps(){
  const [trendingRes, actionRes, comedyRes] = await Promise.all([
    fetch('https://reactflix-alien0s.vercel.app/api/trending'),
    fetch('https://reactflix-alien0s.vercel.app/api/action'),
    fetch('https://reactflix-alien0s.vercel.app/api/comedy')
  ]);

  const [trending,action,comedy] = await Promise.all([
    trendingRes.json(),
    actionRes.json(),
    comedyRes.json()
  ]);

  return{
    props: {
      trendingProps: trending.list,
      actionProps: action.list,
      comedyProps: comedy.list
    }
  };
}
